### ISSUE TITLE
Missing Uninstall and Update in Documentation

### ISSUE THREAD

**Issue by Wintermute2k6** [LordHepipud/icinga-windows-service#3]
As there are two dedicated Commands Uninstall-IcingaFrameworkService.psm1 and Install-IcingaFrameworkUpdate.psm1

Maybe there should be at least a small Documentation of invoking those to update or remove the Service by itself without the additional usage of the kickstart script.

Regards

David

**Comment by LordHepipud** [comment]
This was already introduced with Icinga for Windows v1.6.0
