### ISSUE TITLE
Seperate install-icingaServiceUpdate module

### ISSUE THREAD

**Issue by Wintermute2k6** [LordHepipud/icinga-windows-service#4]
It might be useful to have a seperate module that just updates the service itself without touching the framework.
At the moment we just have the install-icingaFrameworkUpdate.psm which updates the whole installation maybe we have in the future a reason to update the service seperately due to windows changes.

**Comment by LordHepipud** [comment]
This was already introduced with Icinga for Windows v1.6.0 and the repository manager.
